-- M5: thanh toán qua payOS (SPEC mục 2, 3, 8).
-- orders thêm số đơn cho payOS, link và chuỗi QR, mã giao dịch ngân hàng, ai xác nhận.
-- Hai hàm xác nhận và hoàn tiền đổi orders và entitlements trong một giao dịch.
-- Chỉ server (service role) gọi được. Người dùng vẫn chỉ đọc đơn của mình, không ghi được.

alter table public.orders
  add column order_number bigint generated by default as identity (start with 100001),
  add column checkout_url text,
  add column qr_code text,
  add column bank_ref text,
  add column paid_by text;

alter table public.orders add constraint orders_order_number_key unique (order_number);

-- Xác nhận đơn: pending hoặc expired (tiền tới sau khi link hết hạn) thành paid,
-- cộng ngày Premium: premium_until = greatest(premium_until, now()) + số ngày của gói.
-- Gọi hai lần (webhook gửi lại, admin bấm lại) thì lần sau không cộng thêm.
-- p_paid_amount null khi admin xác nhận tay; có giá trị thì phải đủ số tiền của đơn.
create function public.confirm_order(p_order_id uuid, p_bank_ref text, p_paid_by text, p_paid_amount int)
returns jsonb
language plpgsql
set search_path = ''
as $$
declare
  v_order public.orders;
  v_days int;
  v_until timestamptz;
begin
  select * into v_order from public.orders where id = p_order_id for update;
  if not found then
    return jsonb_build_object('status', 'not_found');
  end if;
  if v_order.status = 'paid' then
    return jsonb_build_object('status', 'already_paid');
  end if;
  if v_order.status not in ('pending', 'expired') then
    return jsonb_build_object('status', 'not_pending');
  end if;
  if p_paid_amount is not null and p_paid_amount < v_order.amount then
    return jsonb_build_object('status', 'amount_mismatch');
  end if;

  v_days := case v_order.plan when '30d' then 30 when '90d' then 90 end;

  update public.orders
  set status = 'paid', paid_at = now(), bank_ref = p_bank_ref, paid_by = p_paid_by
  where id = p_order_id;

  update public.entitlements
  set premium_until = greatest(coalesce(premium_until, now()), now()) + make_interval(days => v_days)
  where user_id = v_order.user_id
  returning premium_until into v_until;

  return jsonb_build_object('status', 'paid', 'premium_until', v_until, 'user_id', v_order.user_id);
end;
$$;

-- Hoàn tiền: paid thành refunded, premium_until về hiện tại (SPEC mục 3). Tiền trả lại do chủ dự án chuyển tay.
create function public.refund_order(p_order_id uuid)
returns jsonb
language plpgsql
set search_path = ''
as $$
declare
  v_order public.orders;
begin
  select * into v_order from public.orders where id = p_order_id for update;
  if not found then
    return jsonb_build_object('status', 'not_found');
  end if;
  if v_order.status <> 'paid' then
    return jsonb_build_object('status', 'not_paid');
  end if;

  update public.orders set status = 'refunded' where id = p_order_id;
  update public.entitlements set premium_until = now() where user_id = v_order.user_id;

  return jsonb_build_object('status', 'refunded');
end;
$$;

revoke execute on function public.confirm_order(uuid, text, text, int) from public, anon, authenticated;
revoke execute on function public.refund_order(uuid) from public, anon, authenticated;
grant execute on function public.confirm_order(uuid, text, text, int) to service_role;
grant execute on function public.refund_order(uuid) to service_role;
